articles/urls.py
from django.urls import path
from . import views

app_name = 'articles'

# www.domain.com/articles/__
urlpatterns = [
    path('', views.index, name='index'),  # articles:index
    path('create/', views.create, name='create'),
    path('<int:article_pk>/', views.detail, name='detail'),
]

myform/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    # articles/로 오면 일단 articles.urls로 가세요
    path('articles/', include('articles.urls')),
    path('admin/', admin.site.urls),
]

articles/models.py
from django.db import models

# Create your models here.
class Article(models.Model):
    title = models.CharField(max_length=20)
    content = models.TextField()
    created_at = models.DateTimeField(auto_now_add=True)
    # 데이터 업데이트 되면 언제든지 해당 시간 추가
    updated_at = models.DateTimeField(auto_now=True)


    class Meta:
        ordering = ('-pk', )

    def __str__(self):
        return f'{self.pk} - {self.title}'
    

articles/forms.py
from django import forms

# form 쓰는 이유? 사용자가 건네주는 입력값을 form이라는 class가 한번에 받아서 유효성 확인 가능하기 때문에 사용함
# 유효성 확인 후, 검증된 데이터 form에서 가져와서 씀(그냥 raw data를 바로 받아오는 거보다 나음)

# 사용자에게 입력받는 field 만 작성
class ArticleForm(forms.Form):
    title = forms.CharField(
        max_length=20,
        label='제목',
        widget=forms.TextInput(
            attrs={
                'placeholder': '제목 입력할 `수` 있어요',
            }
        ),

    )

    content = forms.CharField(
        label='내용',
        widget=forms.Textarea(
            attrs={
                'placeholder': '내용 입력할 `수` 있어요',
                'rows': 5,
                'cols': 50,
            }
        )
    )

articles/views.py
from django.shortcuts import render, redirect, get_object_or_404
from .models import Article
from .forms import ArticleForm

# 모든 aricle을 보여주는 페이지
def index(request):
    # 모든 article 담는 과정
    articles = Article.objects.all()
    context = {'articles': articles}
    return render(request, 'articles/index.html', context)

# GET으로 들어오면 생성하는 페이지 renderin'
# POST로 들어오면 생성하는 로직 수행
def create(request):
    if request.method == 'POST':
        form = ArticleForm(request.POST)
        # 사용자가 입력한 데이터 유효성 확인
        if form.is_valid():
            # forms.py에서 걸러진 깨끗한 데이터로부터 해당 데이터 가져오는 작업
            title = form.cleaned_data.get('title')
            content = form.cleaned_data.get('content')
            # form 이 valid 한 경우에만 데이터 저장
            article = Article(title=title, content=content)
            article.save()
            return redirect('articles:index')
        # else:
        #     # valid 한 값이 있지 않은 form을 다시 보내주는 작업
        #     # (이상한 값이 있으면 다시 입력하라는 화면 보여주는 것; 중간에 잘못 입력하더라도 입력값을 그대로 넣은 채로 다시 form 보내주면서 다시 입력하라는 요청)
        #     context = {'form': form}
        #     return render(request, 'articles/create.html', context)
    else:
        form = ArticleForm()
    # context = {'form':form}, return이 중복되니까, 코드를 줄일 수 있다.
    context = {'form': form} 
    return render(request, 'articles/create.html', context)

def detail(request, article_pk):
    article = get_object_or_404(Article, pk=article_pk)
    context = {'article': article}
    return render(request, 'articles/detail.html', context)

articles/templates/articles/create.html
{% extends 'base.html' %}

{% block title %}Article 생성{% endblock title %}

{% block body %}
<h1>새로운 아티클 생성</h1>
<a href=" {% url 'articles:index' %} ">[뒤로가기]</a>
<hr>
{% comment %} action에 아무것도 안 적으면, /articles/create/ {% endcomment %}
<form action="" method="POST">
  {% csrf_token %}
  {% comment %} view 함수로부터 받아온 form 불러오는 작업 {% endcomment %}
  {{ form.as_p }}
  <button type="submit">생성하기</button>
</form>

{% endblock body %}

articles/templates/articles/detail.html
{% extends 'base.html' %}

{% block title %} 아티클:Article{% endblock title %}

{% block body %}
<h1>{{ article.title }}</h1>
<p>{{ article.created_at }}</p>
<hr>
<p>{{ article.content }}</p>
<hr>
<a href="{% url 'articles:index' %}">뒤로가기</a>
{% endblock body %}

articles/templates/articles/index.html
{% extends 'base.html' %}


{% block title %}Articles 페이지{% endblock title %}
{% block body %} 
<h1>Articles</h1>
<a href="{% url 'articles:create' %}">[New]</a>
<hr>
{% for article in articles %}
<div>
  <h3>{{ article.pk }}. {{ article.title }}</h3>
  <p>{{ article.created_at }}</p>
  <a href="{% url 'articles:detail' article.pk %}">[Detail]</a>
</div>
<br>
{% empty %}
<p>아직 게시글이 없습니다..</p>
{% endfor %}
{% endblock body %}

myform/templates/base.html
<!DOCTYPE html>
<html lang="ko">
<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <meta http-equiv="X-UA-Compatible" content="ie=edge">
  <title> {% block title %}{% endblock title %}</title>
</head>
<body>
  {% block body %}
  {% endblock body %}
</body>
</html>